language: python

sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build and push image
      script:
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - docker build -t diemol/chrome-remote-cdp .
      - docker push diemol/chrome-remote-cdp:latest
